### ISSUE TITLE
Get the Program Running and Take Some Screenshots

### ISSUE THREAD

**Issue by keenanjohnson** [keenanjohnson/quantum-eprocs#1]
I was able to get the application running at least enough to serve the landing page locally.

For some reason, I had to run the npm install command again after opening up the docker container. This is odd because I thought 

```
npm install --no-save
pm2 start ecosystem.config.js
```

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/2559382/187704987-201ae791-eb18-452f-9817-eeaff56c260a.png">

Unfortunately, I can't login as there is some problem with the google authentication.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/2559382/187706308-8a1d4d50-45f2-4503-9586-2227b0d13d8d.png">

I need to figure out how to disable or fix the authentication to just get some screenshots of the app.

```
Error: Unknown authentication strategy "google"
    at attempt (/workspaces/quantum-eprocs/node_modules/passport/lib/middleware/authenticate.js:173:37)
    at authenticate (/workspaces/quantum-eprocs/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/workspaces/quantum-eprocs/node_modules/express/lib/router/layer.js:95:5)
    at next (/workspaces/quantum-eprocs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/workspaces/quantum-eprocs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/workspaces/quantum-eprocs/node_modules/express/lib/router/layer.js:95:5)
    at /workspaces/quantum-eprocs/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/workspaces/quantum-eprocs/node_modules/express/lib/router/index.js:335:12)
    at next (/workspaces/quantum-eprocs/node_modules/express/lib/router/index.js:275:10)
    at /workspaces/quantum-eprocs/node_modules/connect-flash/lib/flash.js:21:5
    at Layer.handle [as handle_request] (/workspaces/quantum-eprocs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/workspaces/quantum-eprocs/node_modules/express/lib/router/index.js:317:13)
    at /workspaces/quantum-eprocs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/workspaces/quantum-eprocs/node_modules/express/lib/router/index.js:335:12)
    at next (/workspaces/quantum-eprocs/node_modules/express/lib/router/index.js:275:10)
    at strategy.pass (/workspaces/quantum-eprocs/node_modules/passport/lib/middleware/authenticate.js:325:9)
```

**Comment by keenanjohnson** [comment]
Running the mongoDB docker container locally with these commands

```
docker pull mongo
docker run -d  --name mongo-on-docker  -p 27888:27017 -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=secret mongo
```
